### PR TITLE
purge release artefacts from repo

### PR DESCRIPTION
**Pull request by akrherz**
I'm working on getting your library onto conda-forge and these release/build artefacts are causing a bit of grief.

### CODE REVIEW

**Comment by a-urq** [comment]
Sorry this took so long for me to see. It looks good to me, got it merged in. 

Will future updates be taken care of as well or is this just for the current version?

**Comment by akrherz** [comment]
Hi @a-urq , no need to apologize.  In general, you want to try to keep binary / complied stuff out of your source code repository and especially the source tree, so that it does not get bundled into releases.  I think cutting a new release would fix my issue upstream with conda-forge.  Up to you.

**Comment by a-urq** [comment]
Done https://github.com/a-urq/ecape-parcel-py/releases/tag/v1.2.0.2

**Comment by akrherz** [comment]
Thanks @a-urq , please upload the release to pypi

**Comment by a-urq** [comment]
https://pypi.org/project/ecape-parcel/1.2.0.2/

**Pull request merged**
